version: "3"
services:
  sonarr:
    image: linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SONARR_CONFIG_DIR}:/config
      - ${MEDIA_DIR}:/media
    ports:
      - ${SONARR_PORT}:8989
