version: "3"
services:
  transmission:
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TRANSMISSION_CONFIG_DIR}:/config
      - ${TORRENT_DIR}:/media/torrents
    env_file:
      - ./openvpn.env
    environment:
      - LOCAL_NETWORK=192.168.0.0/24
      - PUID=1000
      - GUID=1000
      - TRANSMISSION_HOME=/config
      - TRANSMISSION_DOWNLOAD_DIR=/media/torrents/completed
      - TRANSMISSION_INCOMPLETE_DIR=/media/torrents/incomplete
      - TRANSMISSION_WATCH_DIR=/media/torrents/watch
    ports:
      - ${TRANSMISSION_PORT}:9091

  sonarr:
    image: linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SONARR_CONFIG_DIR}:/config
      - ${MEDIA_DIR}:/media
    ports:
      - ${SONARR_PORT}:8989

  radarr:
    image: linuxserver/radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${RADARR_CONFIG_DIR}:/config
      - ${MEDIA_DIR}:/media
    ports:
      - ${RADARR_PORT}:7878

  jackett:
    image: linuxserver/jackett
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${JACKETT_CONFIG_DIR}:/config
    ports:
      - ${JACKETT_PORT}:9117

  plex:
    image: linuxserver/plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - ./plex.env
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=public
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PLEX_CONFIG_DIR}:/config
      - ${TV_DIR}:/media/tv
      - ${MOVIE_DIR}:/media/movies
      - ${MUSIC_DIR}:/media/music

  monica-db:
    image: mysql:5.7
    volumes:
      - /wish/app-data/monica-db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret

  monica:
    image: monicahq/monicahq
    depends_on:
      - monica-db
    volumes:
      - /wish/app-data/monica:/var/www/monica/storage
    environment:
      - APP_KEY=IjVuPC2jO8RXTInlK0PH5rJYcNFi2PlF
      - DB_HOST=monica-db
      - APP_ENV=local
      - APP_DISABLE_SIGNUP=false
    ports:
      - 8080:80
  # nextcloud:
  #   image: linuxserver/nextcloud
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /path/to/appdata:/config
  #     - /path/to/data:/data
  #   ports:
  #     - 443:443
  #   restart: unless-stopped
