version: "3"
services:
  plex:
    image: linuxserver/plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - ./container.env
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=public
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PLEX_CONFIG_DIR}:/config
      - ${TV_DIR}:/media/tv
      - ${MOVIE_DIR}:/media/movies
      - ${MUSIC_DIR}:/media/music
