version: "3"
services:
  radarr:
    image: linuxserver/radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${RADARR_CONFIG_DIR}:/config
      - ${MEDIA_DIR}:/media
    ports:
      - ${RADARR_PORT}:7878
