---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rtmp
  labels:
    app.kubernetes.io/name: nginx-rtmp
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: nginx-rtmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-rtmp
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: nginx-rtmp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-rtmp
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: nginx-rtmp
    spec:
      containers:
        - name: nginx-rtmp
          image: tiangolo/nginx-rtmp
          imagePullPolicy: Always
          ports:
            - name: rtmp
              containerPort: 1935
              hostPort: 1935
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 150m
              memory: 200Mi
